---
- name: Provision App
  hosts: production-app
  user: root
  gather_facts: true
  sudo: true

  vars:
    domain_name: "{{app_name}}.com"
    environment_name: production

  vars_files: 
    - vars/common.yml
    - secret/production.yml

  roles:
    - user
    - common
    - environment_vars
    - ruby-2.1.2
    - nginx


- name: Provision Util
  hosts: production-util
  user: root
  gather_facts: true
  sudo: true

  vars:
    domain_name: "{{app_name}}.com"
    environment_name: production

  vars_files: 
    - vars/common.yml
    - vars/elasticsearch.yml
    - secret/production.yml

  roles:
    - user
    - common
    - environment_vars
    - ruby-2.1.2
    - postgres
    - redis
    - sidekiq
    - ansible-elasticsearch
